"""Convert alert severity to string for robustness

Revision ID: ecf129853a14
Revises: c45e91c5237c
Create Date: 2026-05-19 16:40:25.176759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf129853a14'
down_revision: Union[str, Sequence[str], None] = 'c45e91c5237c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'severity',
               existing_type=postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alertseverity'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'severity',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('INFO', 'WARNING', 'CRITICAL', name='alertseverity'),
               existing_nullable=False)
    # ### end Alembic commands ###